export const winBlockPrograms = [
  "RecExperts.exe",
  "camrecorder.exe",
  "SunloginClient.exe",
  "HyCam2.exe",
  "FSCapture.exe",
  "capture-pro.exe",
  "EasyCapture.EXE",
  "ApowersoftScreenRecorder.exe",
  "GOMCam.exe",
  "CamRecorder.exe",
  "WinSnap.exe",
  "wingrab.exe",
  "SnapShot.exe",
  "My Screen Recorder.exe",
  "AnyDesk",
  "ScreenRe.exe",
  "S4BScreenRecorder.exe",
  "Screenpresso.exe",
  "ScreenRecorderPro.exe",
  "GoPlay Editor.exe",
  "UltraCapture.EXE",
  "ACA Capture",
  "AnyCapture.EXE",
  "ScreenpressoCapture.exe",
  "AutoScreenCapture2.exe",
  "Apowersoft.ScreenRecorderPro3.exe",
  "WMCap.exe",
  "captura.exe",
  "CScreenie.exe",
  "DuckCapture.exe",
  "EasyCapture.EXE",
  "escr-1.exe",
  "Flash32.exe",
  "FoxArcMovieEditor.EXE",
  "paidashi.exe",
  "Greenshot.exe",
  "BbbVCapture.exe",
  "obs",
  "TuneFab Screen Recorder.exe",
  "HandySnap.exe",
  "HoverSnap.exe",
  "Horizon33.exe",
  "jetScreenshot.exe",
  "KingKongCapture.exe",
  "lightscreen.exe",
  "LightShot.exe",
  "Magic Screenshot.exe",
  "picpick.exe",
  "PixClip.exe",
  "PrintScreenDeluxe.exe",
  "PrtScr.exe",
  "ScreenCapture.exe",
  "ScreenCapturePrint.exe",
  "ScreenGrab.EXE",
  "AutoScreenRecorder.exe",
  "scrprt30.exe",
  "SRip32.exe",
  "screenshooter.exe",
  "ScreenshotCaptor.exe",
  "Screeny.exe",
  "ScreenVCR.exe",
  "ScreenCapturer.exe",
  "ScreenShot.exe",
  "SliQScrCap.exe",
  "StepShot.exe",
  "TinyTake by MangoApps.exe",
  "SSCapture.exe",
  "WinShot.exe",
  "recorder.exe",
  "xShots.exe",
  "SocialScreenCapture.exe",
  "MyScreenCaptureDemo.exe",
  "ScreenVirtuoso",
  "2CaptureEasy.EXE",
  "ShareX.exe",
  "ScnRec.exe",
  "CaptureMyScreen.exe",
  "ReplayVideo.exe",
  "SMM_HyperCam.exe",
  "Capture.EXE",
  "EasyScreenShot.exe",
  "Screenshot.exe",
  "MRGetScreen.exe",
  "NuGenScreenCAP.exe",
  "Quick Screener.exe",
  "SaveSnap.exe",
  "ScreenShooter.exe",
  "Screen Shot Pro.exe",
  "ScreenGrabber.exe",
  "videocapture.exe",
  "ScreenAviCam.exe",
  "vscap.EXE",
  "Camtica2.exe",
  "IEMonitor.EXE",
  "ly.exe",
  "FlashBack Recorder.exe",
  "TeamViewer.exe",
  "Monosnap.exe",
  "Filmora.exe",
  "AnyMP4 Screen Recorder.exe",
  "HotCapture.exe",
  "Action.exe",
  "AdobeCaptivate.exe",
  "ALLCapture.exe",
  "amcap.exe",
  "AshSnap.exe",
  "atauthor.exe",
  "AVSScreenCapture.exe",
  "Bdcam.exe",
  "Captivate.exe",
  "CaptureShow.exe",
  "Online Screen Recorder.exe",
  "CsmRec.EXE",
  "CYYScreenREC.exe",
  "debut.exe",
  "dvbdream.exe",
  "EasyCam.exe",
  "ExtraWebcam.exe",
  "FlashDemo.exe",
  "FSRecorder.exe",
  "InstantDemo.EXE",
  "iScreenRecorder.exe",
  "jsmrp.exe",
  "Aiseesoft Screen Recorder.exe",
  "KKcapture.exe",
  "Main-1.exe",
  "My Screen Recorder Pro.exe",
  "WMC.exe",
  "Screen2Avi.exe",
  "Screen2Exe.EXE",
  "screencap.exe",
  "ScreenHunter.exe",
  "ScreenRecorder.exe",
  "ScreenVCR.exe",
  "SFlash.EXE",
  "SinaVirtualCamera",
  "SMM_HyperCam.exe",
  "StreamCloner.exe",
  "Streaming-Video-Recorder.exe",
  "TestAssistant Recorder.exe",
  "TinyTaskPortable.exe",
  "VideoRecord.exe",
  "ViewletCam.EXE",
  "VSSCap.exe",
  "Vstudio.EXE",
  "Wirecast.exe",
  "WMR.exe",
  "YouCam.exe",
  "KK.exe",
  "HprSnap7.exe",
  "RdfSnap.exe",
  "Recorder.exe",
  "CamtasiaStudio.exe",
  "wdswmtdsktp.exe",
  "vlc.exe",
  "Icecream Screen Recorder",
  "GamePanel.exe",
  "CaptureShow.EXE",
  "DesktopCap.exe",
  "ScreenCAP.exe",
  "GFExperience.exe",
  "ScreenToGif.exe",
  "BandicamPortable.exe",
  "oCam.exe",
  "Screencast.exe",
  "EVCapture.exe",
  "Apowersoft Video Converter.exe",
  "Online Screen Recorder.exe",
  "obs64.exe",
  "EasiAction.exe",
  "AVCUltimate.exe",
  "ActivePresenter.exe",
  "cutescreenrecorder.exe",
  "Screen-Recording-Suite.exe",
  "4Videosoft Screen Capture.exe",
  "FSRecord.exe",
  "XSplit.Core.exe",
  "ACDSeeScreenRecorder.exe",
  "DemoCreator.exe",
  "Gecata.exe",
  "Zoom Meetings",
  "BlueJeans.exe",
  "Adobe Premiere Pro.exe",
  "AfterFX.exe",
  "EEScreen.exe",
  "spacedeskServiceTray.exe",
  "Wondershare Studio",
  "Zalo.exe",
  "ZaloCall.exe",
  "ZaloCap.exe",
  "WhatsApp.exe",
  "Messenger.exe",
  "KakaoTalk.exe",
  "Discord.exe",
  "Telegram.exe",
  "tsetup.exe",
  "Line.exe",
  "Viber.exe",
  "Skype.exe",
  "SkypeApp.exe",
  "Signal.exe",
  "WeChat.exe",
  "slack.exe",
  "Teams.exe",
  "Zoom.exe",
  "icq.exe",
  "YahooMessenger.exe",
];

export const webBlockList = [
  {
    service: "Facebook",
    domains: [
      "facebook.com",
      "www.facebook.com",
      "m.facebook.com",
      "web.facebook.com",
      "connect.facebook.net",
      "static.xx.fbcdn.net",
      "scontent.xx.fbcdn.net",
    ],
  },
  {
    service: "Messenger",
    domains: [
      "messenger.com",
      "www.messenger.com",
      "edge-chat.facebook.com",
      "fbsbx.com",
    ],
  },
  {
    service: "WhatsApp",
    domains: [
      "web.whatsapp.com",
      "whatsapp.com",
      "whatsapp.net",
      "mmg.whatsapp.net",
      "media.fss.whatsapp.net",
    ],
  },
  {
    service: "Viber",
    domains: ["viber.com", "www.viber.com", "api.viber.com", "media.viber.com"],
  },
  {
    service: "Line",
    domains: [
      "line.me",
      "www.line.me",
      "api.line.me",
      "cdn.line-apps.com",
      "obs.line-scdn.net",
      "ga2.line.naver.jp",
    ],
  },
  {
    service: "Telegram",
    domains: [
      "telegram.org",
      "web.telegram.org",
      "api.telegram.org",
      "t.me",
      "cdn-telegram.org",
      "telegram.me",
    ],
  },
  {
    service: "Zalo",
    domains: [
      "zalo.me",
      "www.zalo.me",
      "chat.zalo.me",
      "pc-api.zalo.me",
      "friend.zalo.me",
      "wpa.zalo.me",
      "v4.chat.zalo.me",
      "api.zaloapp.com",
      "oapi.zaloapp.com",
      "update.zaloapp.com",
      "log.zaloapp.com",
      "stc.zdn.vn",
      "dl-zalo.zdn.vn",
      "photo.zadn.vn",
      "video.zadn.vn",
      "res-zalo.zadn.vn",
      "stc-zaloprofile.zdn.vn",
      "stc-sp.zdn.vn",
      "res-hn.zadn.vn",
      "res-hcm.zadn.vn",
    ],
  },
  {
    service: "KakaoTalk",
    domains: [
      "kakaocorp.com",
      "daumcdn.net",
      "talk.kakao.com",
      "api.kakao.com",
      "auth.kakao.com",
      "friend.kakao.com",
    ],
  },
  {
    service: "Discord",
    domains: [
      "discord.com",
      "www.discord.com",
      "discordapp.com",
      "status.discord.com",
      "cdn.discordapp.com",
      "media.discordapp.net",
      "gateway.discord.gg",
      "images-ext-1.discordapp.net",
    ],
  },
  {
    service: "Skype",
    domains: [
      "skype.com",
      "www.skype.com",
      "api.skype.com",
      "login.skype.com",
      "join.skype.com",
      "swx.cdn.skype.com",
    ],
  },
  {
    service: "Signal",
    domains: [
      "signal.org",
      "api.signal.org",
      "cdn.signal.org",
      "updates.signal.org",
    ],
  },
  {
    service: "WeChat",
    domains: [
      "wechat.com",
      "www.wechat.com",
      "weixin.qq.com",
      "wx.qq.com",
      "web.wechat.com",
      "res.wx.qq.com",
    ],
  },
  {
    service: "Slack",
    domains: [
      "slack.com",
      "www.slack.com",
      "api.slack.com",
      "files.slack.com",
      "downloads.slack-edge.com",
      "slack-edge.com",
    ],
  },
  {
    service: "Microsoft Teams",
    domains: [
      "teams.microsoft.com",
      "statics.teams.microsoft.com",
      "login.microsoftonline.com",
      "skypeassets.com",
      "teams.cdn.office.net",
    ],
  },
  {
    service: "Zoom",
    domains: [
      "zoom.us",
      "www.zoom.us",
      "api.zoom.us",
      "zoom.us.cn",
      "zoomcloud.cn",
      "st1.zoom.us",
    ],
  },
  {
    service: "Google Meet",
    domains: [
      "meet.google.com",
      "gstatic.com",
      "meetings.googleapis.com",
      "meetings.google.com",
      "hangouts.google.com",
      "hangouts.googleapis.com",
    ],
  },
];
